name: AnticheatScoreboard
main: cc.funkemunky.scoreboard.AnticheatScoreboard
author: funkemunky
version: ${project.version}
depend: [Atlas]
softdepend: [KauriLoader, AAC, Spartan, Reflex, NoCheatPlus, Iris, FeatherBoard]